version: 2.1
executors:
  linux:
    docker:
      - image: circleci/node:14-browsers

commands:
  yarn_install:
    steps:
      - restore_cache:
          name: Restoring dependency cache
          key: yarn-v9-{{arch}}-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Saving dependency cache
          key: yarn-v9-{{arch}}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/AppData/Local/Yarn/Cache
            - ~/Library/Caches/Yarn

jobs:
  test:
    executor: <<parameters.executor>>
    parameters:
      executor:
        type: executor
        default: "linux"
    steps:
      - checkout
      - yarn_install
      - run:
          name: Prepack
          command: yarn prepack
      - run:
          name: Running tests
          command: yarn test
workflows:
  test:
    jobs:
      - test