name: Release

on:
  push:
    branches:
      - main

jobs:
  publish-releases:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Release
      uses: thefrontside/actions/synchronize-with-npm@v1.9
      with:
        before_all: yarn prepack
        npm_publish: yarn publish
      env:
        GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
